### ISSUE TITLE
Connect memberships to CiviSEPA mandates

### ISSUE THREAD

**Issue by systopia** [Project60/org.project60.membership#10]
Enable the system to "connect" memberships to SEPA mandates, so that
* the new contributions (installments) get automatically assigned
* the memberships get automatically extended

**Comment by jaapjansma** [comment]
I have been testing this since yesterday and with help from @systopia found a couple of issues and could fix them. In my local environment this is all working now. I will submit my fixes.

**Comment by jaapjansma** [comment]
See PR: https://github.com/Project60/org.project60.membership/pull/17
