### ISSUE TITLE
Extend a membership by completing a contribution

### ISSUE THREAD

**Issue by jaapjansma** [Project60/org.project60.membership#18]
I want to extend the membership period as soon as a pending contribution is set to completed. 

**The use case is:**
I have a membership organisation and I collect membership payment with Sepa Direct Debit. When I create the file the contributions are automaticly linked to the membership (see #10). The contributions are immediatly set to completed as we deal with failures manually. Now I want that the membership is extended with the status current as sson as the contribution is set to completed. 

**Solution:**
Provide a checkbox to enable/disable this functionality from the configuration and then whenever a contribution is updated and the status is set to completed we should extend the membership.

**Comment by jaapjansma** [comment]
I have implemented this below a screenshot of the setting screen
![screenshot from 2018-06-19 17-35-14](https://user-images.githubusercontent.com/4126292/41608150-194c464a-73e8-11e8-95e5-dbcd31f96004.png)

**Comment by systopia** [comment]
@jaapjansma: Sounds/looks great. I'll have a look and merge when I'm back from BRX.

**Comment by jaapjansma** [comment]
@systopia I am going to add another commit to check whether the contribution is completed before extending the membership.

**Comment by jaapjansma** [comment]
I have updated the PR (https://github.com/Project60/org.project60.membership/pull/19). It now triggers when a contribution is completed. It will then check if the contribution is linked with a membership and if so (and the setting is enabled) then it will extend the membership end date. 
![screenshot from 2018-06-20 17-16-38](https://user-images.githubusercontent.com/4126292/41667769-15829ffc-74ae-11e8-9d59-2147b7510001.png)

**Comment by systopia** [comment]
released with ``0.5.1``
