### ISSUE TITLE
Do not update the end date of the membership when it is the first contribution

### ISSUE THREAD

**Issue by jaapjansma** [Project60/org.project60.membership#34]
When a first contribution is set to completed the membership is renewed.

**How to reproduce?**

1. Create a membership _without a payment_
2. Create a sepa mandate
3. Link the mandate to the membership
4. Run the sepa workflow and send the file to the bank
5. Set the created contribution to completed as incoming money is matched

**Expected results**

1. After step 4: a contribution with the status in progress is created
2. After step 5: the membership has status New and the end date is 22 January 2020

**Actual results**

1. After step 4: a contribution with the status in progress is created
2. After step 5: the membership has status New and the end date is **22 January 2021**

**Comment by eth4ever** [comment]
@jaapjansma Is this a optional feature or a (new) standaard procedure? Our use case is that new members make their first membership contribution online (iDeal) and they can choose to do their next payments by direct debit. In this case the first DD, has to extend the membership.

**Comment by jaapjansma** [comment]
It doesn't matter whether the first contribution is a sepa contribution or paid online (iDeal). The first means here the first contribution linked to the membership.

**Comment by eth4ever** [comment]
Great, but very important to document this feature.
