### ISSUE TITLE
Help-button on configurationsite shows wrong help

### ISSUE THREAD

**Issue by Rolf-ROBIN-WOOD** [Project60/org.project60.membership#36]
The help buttons at cancellation shows the wrong help

**Comment by ghost** [comment]
Seems to be fixed in release 0.7-beta1, at least for the German translation. 
There are only two help textes about canceling memberships, refering to date and reason as custom fields. 
Maybe we should close this issue?

**Comment by bjendres** [comment]
> Maybe we should close this issue?

Sounds good.
