### ISSUE TITLE
Remove deprecated function calls

### ISSUE THREAD

**Issue by jensschuppe** [Project60/org.project60.membership#46]
At least `split()` is being used in the current code, e.g. here: https://github.com/Project60/org.project60.membership/blob/91fc74179f62ab79a68a7700237fc1b79ecdd6da/api/v3/Membership/Extend.php#L298

This function had been deprecated since PHP 5.3.0 and removed since PHP 7.0.0.

**Comment by jensschuppe** [comment]
This should be easy using `explode()` instead.

**Comment by jensschuppe** [comment]
Also, that seems to be the only occurence of incompatible language elements, according to a PHPStorm code inspection on the current `new_master` branch (91fc74179f62ab79a68a7700237fc1b79ecdd6da).

**Comment by bjendres** [comment]
@jensschuppe go ahead and fix it there. I'ts called ``new_master`` after a merge mishap, we can rename soon...

**Comment by bjendres** [comment]
@jensschuppe  feel free to create an alpha-release

**Comment by jensschuppe** [comment]
@bjendres I don't have write access or whatever permission is needed for releases, so that'd be your task ;)
