### ISSUE TITLE
Can't select custom field with membership-number in Quicksearch options

### ISSUE THREAD

**Issue by ghost** [Project60/org.project60.membership#59]
I created a custom field for membership number and use it for integration with this extension. It is searchable. 

But there is no possibility to select this field in Quicksearch options. Is something missing or am I doing some other thing wrong?

(Release 0.7-dev, CiviCRM 5.48.0 on WordPress 5.9.3, Ubuntu with PHP 7.4.3)

**Comment by bjendres** [comment]
> But there is no possibility to select this field in Quicksearch options. Is something missing or am I doing some other thing wrong?

I don't think this has anything to do with this extension, the quicksearch options are provided by the CiviCRM core. You might want to have a look at [this](https://civicrm.org/extensions/quicksearch) extension though.

@eptbertram Does that answer your question?

**Comment by ghost** [comment]
dear @bjendres  this extension is obsolet, because it was included in CiviCRM Core from version 5.8.0+ and I can't install it. 

I can see other custom fields in my quicksearch options, but not this one. It's a pity...

**Comment by bjendres** [comment]
Hm, that's a pity indeed. I does feel like it should be possible to add a custom field to the quick search - maybe you could raise a question on [StackExchange](https://civicrm.stackexchange.com/).

**Comment by ghost** [comment]
SE, of course! There was someone with the same problem. 

Quicksearch looks for contacts, not memberships. Creating a new custom field on contact and fill it with the membership id via CiviRules will do the job. 
https://civicrm.stackexchange.com/questions/34233/searchable-custom-field-doesnt-appear-in-quicksearch-options-list-and-is-not-a

**Comment by ghost** [comment]
Hm, can't get CiviRules to write a custom field from membership to a custom nor normal field of a contact. What action shall I use?
