### ISSUE TITLE
PHP 8.0 Compatibility

### ISSUE THREAD

**Issue by abugey** [Project60/org.project60.membership#60]
* [x] Analyse code regarding PHP 8 compatibility
* [ ] Fix deprecations found (to be specified)

**Comment by 0spinboson** [comment]
not compatible with php8, immediately errors out when I try to install it with php8 selected, installs fine after switching to 7.4.

**Comment by bjendres** [comment]
> not compatible with php8, immediately errors out when I try to install it with php8 selected, installs fine after switching to 7.4.

Yes, thank you, that's what this ticket is about. @0spinboson would you be able to help with this, or do some testing?

**Comment by abugey** [comment]
Errors by inspect code feature of PHPStorm in PHP 8.0:
-     PaidByLogic.php: Zeile 723: Illegal array key type
-     SynchroniseLogic.php: Zeile 180: Illegal array key type

**Comment by TobiasVoigt** [comment]
PHP error log entry after upgrading to PHP8.1 (with v0.6.2):

`PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /html/wordpress/wp-content/uploads/civicrm/ext/org.project60.membership/membership.civix.php on line 246`
